### PR TITLE
Frontend for webapp

### PR DESCRIPTION
**Pull request by MD-AZMAL**
Added a basic frontend layout for login,signup and index page

### CODE REVIEW

**Review by thealphadollar — CHANGES_REQUESTED** [review]
Please include screenshots of the web-app in the PR description.

**Comment by MD-AZMAL** [comment]
sure... I'll do it by tonight

**Comment by MD-AZMAL** [comment]
done

**Review by thealphadollar — CHANGES_REQUESTED** [review]
I highly appreciate your efforts but.

@MD-AZMAL I think you misunderstood what we need on the frontend. Please read what the application does, and then ping me on gitter.

**Comment by MD-AZMAL** [comment]
i think you asked for the user signup.... also i haven't yet added the page for uploading drafts

**Pull request closed without merging**
